export const queryKeys = {
  projects: ['projects'] as const,
  project: (id: string) => ['projects', id] as const,
  projectTasks: (projectId: string) => ['projects', projectId, 'tasks'] as const,
  projectMembers: (projectId: string) => ['projects', projectId, 'members'] as const,
  projectEnvVars: (projectId: string) => ['projects', projectId, 'env-vars'] as const,
  projectEnvVarAudit: (projectId: string) => ['projects', projectId, 'env-vars', 'audit'] as const,
  projectDocuments: (projectId: string) => ['projects', projectId, 'documents'] as const,
  chatMessages: (projectId: string) => ['projects', projectId, 'chat'] as const,
  tasks: (params?: Record<string, unknown>) => ['tasks', params ?? {}] as const,
  task: (id: string) => ['tasks', id] as const,
  taskComments: (taskId: string) => ['tasks', taskId, 'comments'] as const,
  teams: ['teams'] as const,
  invitations: ['invitations'] as const,
  notifications: ['notifications'] as const,
  companies: ['companies'] as const,
  search: (params: Record<string, unknown>) => ['search', params] as const,
  auditStats: (projectId?: string) => ['audit', 'stats', projectId ?? 'all'] as const,
  auditActivity: (projectId?: string) => ['audit', 'activity', projectId ?? 'all'] as const,
  billingUsage: ['billing', 'usage'] as const,
};
