export const queryKeys = {
  projects: ['projects'] as const,
  project: (id: string) => ['projects', id] as const,
  projectTasks: (projectId: string) => ['projects', projectId, 'tasks'] as const,
  projectMembers: (projectId: string) => ['projects', projectId, 'members'] as const,
  projectEnvVars: (projectId: string) => ['projects', projectId, 'env-vars'] as const,
  projectEnvVarAudit: (projectId: string) => ['projects', projectId, 'env-vars', 'audit'] as const,
  projectDocuments: (projectId: string) => ['projects', projectId, 'documents'] as const,
  chatChannels: (projectId: string) => ['projects', projectId, 'chat-channels'] as const,
  chatMessages: (projectId: string, channelId: string) =>
    ['projects', projectId, 'chat', channelId] as const,
  tasks: (params?: Record<string, unknown>) => ['tasks', params ?? {}] as const,
  task: (id: string) => ['tasks', id] as const,
  taskComments: (taskId: string) => ['tasks', taskId, 'comments'] as const,
  taskAttachments: (taskId: string) => ['tasks', taskId, 'attachments'] as const,
  /** Nested subtask tree of a task (IMP-240). */
  subtasks: (taskId: string) => ['tasks', taskId, 'subtasks'] as const,
  /** Checklist rows living directly on a task (IMP-240). */
  checklistItems: (taskId: string) => ['tasks', taskId, 'checklist-items'] as const,
  teams: ['teams'] as const,
  invitations: ['invitations'] as const,
  notifications: ['notifications'] as const,
  notificationUnread: ['notifications', 'unread-count'] as const,
  notificationSettings: ['notifications', 'settings'] as const,
  companies: ['companies'] as const,
  company: (id: string) => ['companies', id] as const,
  companyMembers: (id: string) => ['companies', id, 'members'] as const,
  agents: (scope?: Record<string, unknown>) => ['agents', scope ?? {}] as const,
  agent: (id: string) => ['agents', id] as const,
  agentLogs: (agentId: string) => ['agents', agentId, 'logs'] as const,
  search: (params: Record<string, unknown>) => ['search', params] as const,
  auditStats: (projectId?: string) => ['audit', 'stats', projectId ?? 'all'] as const,
  auditActivity: (projectId?: string) => ['audit', 'activity', projectId ?? 'all'] as const,
  billingUsage: ['billing', 'usage'] as const,
};
